### ISSUE TITLE
Modernising npcf

### ISSUE THREAD

**Issue by rubenwardy** [stujones11/minetest-npcf#4]
Is it really necessary to have a separate mod for this? Seems a little weird. Was wondering about the rationale

**Comment by stujones11** [comment]
This is an old mod, there was no colorize modifier or entity name tags when I wrote this. The mod was moved to the old mods section for this very reason.

https://forum.minetest.net/viewtopic.php?f=13&t=7321&start=100#p204485

**Comment by rubenwardy** [comment]
> now most of its 'features' are available via the api

The Minetest lua api?

**Comment by stujones11** [comment]
Yes, that is what I meant, things like colored name tags for npc entities.

**Comment by rubenwardy** [comment]
easy to fix  https://github.com/rubenwardy/minetest-npcf/commit/372c4f2d3082fe69fc75583510bbccc48c4273d2

If it's okay, I'd like to use the code in this mod to make a more up to date mod to make a nice framework

**Comment by stujones11** [comment]
Sorry, I just noticed your PR. looks interesting and would be happy to merge, however, If you think you can do something with this mess I am happy to grant you push access to the repo. I would suggest you use the npcf_ng branch as it is in much better shape than master.

**Comment by stujones11** [comment]
Thank you for accepting the invitation to become a collaborator, hopefully you can revive this project into something useful. I will try to keep an eye on development and can help with any blender stuff if required.

**Comment by rubenwardy** [comment]
You're welcome. Your license is ambiguous - do you mind if I change it to LGPL 2.1 or later for code, and cc0 for textures

**Comment by rubenwardy** [comment]
Would you be able to confirm that the comments here are correct? https://github.com/rubenwardy/minetest-npcf/commit/15f5978c74c14f308afcd1baf9e9c42ad2982927

**Comment by stujones11** [comment]
The License is already LGPL and I would have intended whatever was compatible with the engine, so that's fine and I that agree cc0 more appropriate for the other media.
