### ISSUE TITLE
Duplication bugs in master branch

### ISSUE THREAD

**Issue by stujones11** [stujones11/minetest-npcf#5]
The master branch of this mod is riddled with table duplication bugs since the author, at the time, was completely unaware of how tables in Lua work and thought that new_table = old_table would actually give you a new table. This has been remedied in the npcf_ng branch along with more complete documentation so I propose that it should now become master branch.

@rubenwardy I am not sure if you are able to do that but you could just drop the changed files into master as one big commit. That's all I would probably do anyway unless you have other ideas?

**Comment by rubenwardy** [comment]
I fixes some  npcs_ng had some bugs I've now fixed. It no longer crashes, but needs testing

**Comment by stujones11** [comment]
Should now be fixed.
