### ISSUE TITLE
Merging of my Control Framework

### ISSUE THREAD

**Issue by bell07** [stujones11/minetest-npcf#6]
Hi @rubenwardy, hi @stujones11,
Please have a look to my fork / npcf_ng branch. https://github.com/bell07/minetest-npcf/tree/npcf_ng
The main enhancement is the implemented Control Framework that you find in the file [npcf/control.lua](https://github.com/bell07/minetest-npcf/blob/npcf_ng/npcf/control.lua). The documentation is done at bottom of [README.md](https://github.com/bell07/minetest-npcf/blob/npcf_ng/README.md)
As reference implementation the npcf_guard is already ported to use the framework enhancement.
My question is: How I should create the pull request for this? Because of bigger changes I cannot split them to multiple PR's (ok, the guard changes can be a second PR). Which branch is the right one for the PR? rubenwardy or stujones11?

**Comment by rubenwardy** [comment]
Mine has bug fixes stu's doesn't

**Comment by stujones11** [comment]
Sorry, I have not been tracking this mod since I ceased development of it. I am happy to merge fixes if others think it is worth reviving. @rubenwardy you do have push access here too ;-)

**Comment by stujones11** [comment]
Merged :)
